"""Standard error codes for the application."""

from enum import Enum


class ErrorCode(str, Enum):
    """Enumeration of error codes for the application."""
    
    # Generic Errors
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    DATABASE_ERROR = "DATABASE_ERROR"
    BUSINESS_LOGIC_ERROR = "BUSINESS_LOGIC_ERROR"

    # Auth Errors
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_MAIL_OR_PASSWORD = "INVALID_MAIL_OR_PASSWORD"
    ACCOUNT_PENDING_ACTIVATION = "ACCOUNT_PENDING_ACTIVATION"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    LOGIN_NOT_ALLOWED = "LOGIN_NOT_ALLOWED"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    INVALID_TOKEN_TYPE = "INVALID_TOKEN_TYPE"
    INVALID_TOKEN_PAYLOAD = "INVALID_TOKEN_PAYLOAD"
    USER_NOT_FOUND_OR_CANNOT_LOGIN = "USER_NOT_FOUND_OR_CANNOT_LOGIN"
